vich_uploader:
    db_driver: orm
    mappings:
        image_ingredient:
            uri_prefix: '%image_ingredient%'
            upload_destination: '%kernel.project_dir%/public/images/ingredient'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_update: true
            delete_on_remove: true
    metadata:
        type: attribute