vich_uploader:
    db_driver: orm
    storage: flysystem
    mappings:
        image_ingredient:
            uri_prefix: '%image_ingredient%'
            upload_destination: default.storage
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_update: true
            delete_on_remove: true
    metadata:
        type: attribute